### ISSUE TITLE
Still unable to compile!

### ISSUE THREAD

**Issue by kumuds4** [fantasua/PolarCodesMatLab#1]
I have downloaded latest 3.9.0 CMake.  Still getting following error.CMake Error in CMakeLists.txt:  Failed to run MSBuild command:    MSBuild.exe  to get the value of VCTargetsPath:    CMake Warning (dev) in CMakeLists.txt:  No cmake_minimum_required command is present.  A line of code such as    cmake_minimum_required(VERSION 3.9)  should be added at the top of the file.  The version specified may be lower  if you wish to support older CMake versions for this project.  For more  information run "cmake --help-policy CMP0000".This warning is for project developers.  Use -Wno-dev to suppress it.Configuring incomplete, errors occurred!See also "C:/Users/kumud/Documents/CMake/bin/CMakeFiles/CMakeOutput.log".Note: I have administrative privileged and have CMake in Program files. AFF3CT is in user/Document as you suggested. I see in this latest version there is CMakeLists file. I think, am near to compile but still unable to do so. Thank you for help!
--

**Comment by fantasua** [comment]
Sorry for my poor English.

This code is MatLab code. I haved already uploaded the compiled file, the ".mexw64" file. The ".mexw64" file is complied by the MatyLab's "mex" command. MatLab uses the ".mexw64" file as functions to reduce program's running time.

So there's no need to use CMake to compile. If you need to compile the ".c" and ".cpp" file, use MatLab's own command "mex" to do this.
